server.servlet.context-path=/tienda/api/v1/

app.nombre=Tienda Online
app.lenguaje=es
app.pais=Uruguay
app.autor=Yunier AB

# Conexion a Base de datos
#spring.datasource.platform=mysql
spring.sql.init.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/tienda
spring.datasource.username=root
spring.datasource.password=usbw
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

